services:
  ramenlog-backend:
    build: ./backend
    container_name: ramenlog-backend
    env_file:
      - ./backend/.env
    expose:
      - "8080"
    networks:
      - npm-net
    restart: unless-stopped

#  ramenlog-frontend:
#    build: ./frontend
#    container_name: ramenlog-frontend
#    ports:
#      - "3000:3000"
#    networks:
#      - npm-net
#   restart: unless-stopped

networks:
  npm-net:
    external: true
