services:
  ramenlog-backend:
    build: ./backend
    container_name: ramenlog-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - npm-net
    restart: unless-stopped

#  ramenlog-frontend:
#    build: ./frontend
#    container_name: ramenlog-frontend
#    ports:
#      - "3000:3000"
#    networks:
#      - npm-net
#   restart: unless-stopped

volumes:
  mysql-data:

networks:
  npm-net:
    external: true
