services:
  ramenlog-backend:
    build: ./
    container_name: ramenlog-backend
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - npm-net
    restart: unless-stopped

networks:
  npm-net:
    external: true
