spring:
#  config:
#    import: classpath:application-secret.yml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

jwt:
  secret: ${JWT_SECRET}

google:
  key: ${GOOGLE_KEY}

cloudinary:
  name: ${CLOUDINARY_NAME}
  key: ${CLOUDINARY_KEY}
  secret: ${CLOUDINARY_SECRET}

kakao:
  key: ${KAKAO_KEY}

server:
  port: 8080


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
  api-docs:
    path: /v3/api-docs